// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: panoramic-imitator-message.proto

#ifndef PROTOBUF_panoramic_2dimitator_2dmessage_2eproto__INCLUDED
#define PROTOBUF_panoramic_2dimitator_2dmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace panoramicImitator {
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace panoramicImitator

namespace panoramicImitator {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto();
void protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto();

// ===================================================================

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:panoramicImitator.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double horAngle = 1;
  bool has_horangle() const;
  void clear_horangle();
  static const int kHorAngleFieldNumber = 1;
  double horangle() const;
  void set_horangle(double value);

  // optional double vertAngle = 2;
  bool has_vertangle() const;
  void clear_vertangle();
  static const int kVertAngleFieldNumber = 2;
  double vertangle() const;
  void set_vertangle(double value);

  // @@protoc_insertion_point(class_scope:panoramicImitator.Message)
 private:
  void set_has_horangle();
  void clear_has_horangle();
  void set_has_vertangle();
  void clear_has_vertangle();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double horangle_;
  double vertangle_;
  friend void  protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto_impl();
  friend void  protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_panoramic_2dimitator_2dmessage_2eproto();
  friend void protobuf_ShutdownFile_panoramic_2dimitator_2dmessage_2eproto();

};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Message

// optional double horAngle = 1;
inline bool Message::has_horangle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_horangle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_horangle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_horangle() {
  horangle_ = 0;
  clear_has_horangle();
}
inline double Message::horangle() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.horAngle)
  return horangle_;
}
inline void Message::set_horangle(double value) {
  set_has_horangle();
  horangle_ = value;
  // @@protoc_insertion_point(field_set:panoramicImitator.Message.horAngle)
}

// optional double vertAngle = 2;
inline bool Message::has_vertangle() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_vertangle() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_vertangle() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_vertangle() {
  vertangle_ = 0;
  clear_has_vertangle();
}
inline double Message::vertangle() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.vertAngle)
  return vertangle_;
}
inline void Message::set_vertangle(double value) {
  set_has_vertangle();
  vertangle_ = value;
  // @@protoc_insertion_point(field_set:panoramicImitator.Message.vertAngle)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace panoramicImitator

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_panoramic_2dimitator_2dmessage_2eproto__INCLUDED
