// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: panoramic-imitator-message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "src/protobuf/panoramic-imitator-message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace panoramicImitator {
class MessageDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Message> {};
MessageDefaultTypeInternal _Message_default_instance_;

namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace


const ::google::protobuf::uint32* protobuf_Offsets_panoramic_2dimitator_2dmessage_2eproto() GOOGLE_ATTRIBUTE_COLD;
const ::google::protobuf::uint32* protobuf_Offsets_panoramic_2dimitator_2dmessage_2eproto() {
  static const ::google::protobuf::uint32 offsets[] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, _has_bits_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, horangle_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, vertangle_),
    0,
    1,
  };
  return offsets;
}

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(Message)},
};

static const ::google::protobuf::internal::DefaultInstanceData file_default_instances[] = {
  {reinterpret_cast<const ::google::protobuf::Message*>(&_Message_default_instance_), NULL},
};

namespace {

void protobuf_AssignDescriptors() {
  protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "panoramic-imitator-message.proto", schemas, file_default_instances, protobuf_Offsets_panoramic_2dimitator_2dmessage_2eproto(), factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void protobuf_ShutdownFile_panoramic_2dimitator_2dmessage_2eproto() {
  _Message_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Message_default_instance_.DefaultConstruct();
}

void protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto_impl);
}
void protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto_impl() {
  protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto();
  static const char descriptor[] = {
      "\n panoramic-imitator-message.proto\022\021pano"
      "ramicImitator\".\n\007Message\022\020\n\010horAngle\030\001 \001"
      "(\001\022\021\n\tvertAngle\030\002 \001(\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 101);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "panoramic-imitator-message.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_panoramic_2dimitator_2dmessage_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto_once_);
void protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto_once_,
                 &protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_panoramic_2dimitator_2dmessage_2eproto {
  StaticDescriptorInitializer_panoramic_2dimitator_2dmessage_2eproto() {
    protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto();
  }
} static_descriptor_initializer_panoramic_2dimitator_2dmessage_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Message::kHorAngleFieldNumber;
const int Message::kVertAngleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Message::Message()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:panoramicImitator.Message)
}
Message::Message(const Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&horangle_, &from.horangle_,
    reinterpret_cast<char*>(&vertangle_) -
    reinterpret_cast<char*>(&horangle_) + sizeof(vertangle_));
  // @@protoc_insertion_point(copy_constructor:panoramicImitator.Message)
}

void Message::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&horangle_, 0, reinterpret_cast<char*>(&vertangle_) -
    reinterpret_cast<char*>(&horangle_) + sizeof(vertangle_));
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:panoramicImitator.Message)
  SharedDtor();
}

void Message::SharedDtor() {
}

void Message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Message::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return file_level_metadata[0].descriptor;
}

const Message& Message::default_instance() {
  protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto();
  return *internal_default_instance();
}

Message* Message::New(::google::protobuf::Arena* arena) const {
  Message* n = new Message;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:panoramicImitator.Message)
  if (_has_bits_[0 / 32] & 3u) {
    ::memset(&horangle_, 0, reinterpret_cast<char*>(&vertangle_) -
      reinterpret_cast<char*>(&horangle_) + sizeof(vertangle_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:panoramicImitator.Message)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double horAngle = 1;
      case 1: {
        if (tag == 9u) {
          set_has_horangle();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &horangle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double vertAngle = 2;
      case 2: {
        if (tag == 17u) {
          set_has_vertangle();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &vertangle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:panoramicImitator.Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:panoramicImitator.Message)
  return false;
#undef DO_
}

void Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:panoramicImitator.Message)
  // optional double horAngle = 1;
  if (has_horangle()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->horangle(), output);
  }

  // optional double vertAngle = 2;
  if (has_vertangle()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->vertangle(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:panoramicImitator.Message)
}

::google::protobuf::uint8* Message::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:panoramicImitator.Message)
  // optional double horAngle = 1;
  if (has_horangle()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->horangle(), target);
  }

  // optional double vertAngle = 2;
  if (has_vertangle()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->vertangle(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:panoramicImitator.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:panoramicImitator.Message)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional double horAngle = 1;
    if (has_horangle()) {
      total_size += 1 + 8;
    }

    // optional double vertAngle = 2;
    if (has_vertangle()) {
      total_size += 1 + 8;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:panoramicImitator.Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Message* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Message>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:panoramicImitator.Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:panoramicImitator.Message)
    MergeFrom(*source);
  }
}

void Message::MergeFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:panoramicImitator.Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_horangle()) {
      set_horangle(from.horangle());
    }
    if (from.has_vertangle()) {
      set_vertangle(from.vertangle());
    }
  }
}

void Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:panoramicImitator.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:panoramicImitator.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::Swap(Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Message::InternalSwap(Message* other) {
  std::swap(horangle_, other->horangle_);
  std::swap(vertangle_, other->vertangle_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Message::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  return file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Message

// optional double horAngle = 1;
bool Message::has_horangle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Message::set_has_horangle() {
  _has_bits_[0] |= 0x00000001u;
}
void Message::clear_has_horangle() {
  _has_bits_[0] &= ~0x00000001u;
}
void Message::clear_horangle() {
  horangle_ = 0;
  clear_has_horangle();
}
double Message::horangle() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.horAngle)
  return horangle_;
}
void Message::set_horangle(double value) {
  set_has_horangle();
  horangle_ = value;
  // @@protoc_insertion_point(field_set:panoramicImitator.Message.horAngle)
}

// optional double vertAngle = 2;
bool Message::has_vertangle() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Message::set_has_vertangle() {
  _has_bits_[0] |= 0x00000002u;
}
void Message::clear_has_vertangle() {
  _has_bits_[0] &= ~0x00000002u;
}
void Message::clear_vertangle() {
  vertangle_ = 0;
  clear_has_vertangle();
}
double Message::vertangle() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.vertAngle)
  return vertangle_;
}
void Message::set_vertangle(double value) {
  set_has_vertangle();
  vertangle_ = value;
  // @@protoc_insertion_point(field_set:panoramicImitator.Message.vertAngle)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace panoramicImitator

// @@protoc_insertion_point(global_scope)
