// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: panoramic-imitator-message.proto

#ifndef PROTOBUF_panoramic_2dimitator_2dmessage_2eproto__INCLUDED
#define PROTOBUF_panoramic_2dimitator_2dmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace panoramicImitator {
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Message_Angles;
class Message_AnglesDefaultTypeInternal;
extern Message_AnglesDefaultTypeInternal _Message_Angles_default_instance_;
class Message_Frame;
class Message_FrameDefaultTypeInternal;
extern Message_FrameDefaultTypeInternal _Message_Frame_default_instance_;
}  // namespace panoramicImitator

namespace panoramicImitator {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto();
void protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto();

// ===================================================================

class Message_Angles : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:panoramicImitator.Message.Angles) */ {
 public:
  Message_Angles();
  virtual ~Message_Angles();

  Message_Angles(const Message_Angles& from);

  inline Message_Angles& operator=(const Message_Angles& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message_Angles& default_instance();

  static inline const Message_Angles* internal_default_instance() {
    return reinterpret_cast<const Message_Angles*>(
               &_Message_Angles_default_instance_);
  }

  void Swap(Message_Angles* other);

  // implements Message ----------------------------------------------

  inline Message_Angles* New() const PROTOBUF_FINAL { return New(NULL); }

  Message_Angles* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message_Angles& from);
  void MergeFrom(const Message_Angles& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message_Angles* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double horAngle = 1;
  bool has_horangle() const;
  void clear_horangle();
  static const int kHorAngleFieldNumber = 1;
  double horangle() const;
  void set_horangle(double value);

  // required double vertAngle = 2;
  bool has_vertangle() const;
  void clear_vertangle();
  static const int kVertAngleFieldNumber = 2;
  double vertangle() const;
  void set_vertangle(double value);

  // @@protoc_insertion_point(class_scope:panoramicImitator.Message.Angles)
 private:
  void set_has_horangle();
  void clear_has_horangle();
  void set_has_vertangle();
  void clear_has_vertangle();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double horangle_;
  double vertangle_;
  friend void  protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto_impl();
  friend void  protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_panoramic_2dimitator_2dmessage_2eproto();
  friend void protobuf_ShutdownFile_panoramic_2dimitator_2dmessage_2eproto();

};
// -------------------------------------------------------------------

class Message_Frame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:panoramicImitator.Message.Frame) */ {
 public:
  Message_Frame();
  virtual ~Message_Frame();

  Message_Frame(const Message_Frame& from);

  inline Message_Frame& operator=(const Message_Frame& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message_Frame& default_instance();

  static inline const Message_Frame* internal_default_instance() {
    return reinterpret_cast<const Message_Frame*>(
               &_Message_Frame_default_instance_);
  }

  void Swap(Message_Frame* other);

  // implements Message ----------------------------------------------

  inline Message_Frame* New() const PROTOBUF_FINAL { return New(NULL); }

  Message_Frame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message_Frame& from);
  void MergeFrom(const Message_Frame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message_Frame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 height = 1;
  bool has_height() const;
  void clear_height();
  static const int kHeightFieldNumber = 1;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // required int32 width = 2;
  bool has_width() const;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:panoramicImitator.Message.Frame)
 private:
  void set_has_height();
  void clear_has_height();
  void set_has_width();
  void clear_has_width();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 width_;
  friend void  protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto_impl();
  friend void  protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_panoramic_2dimitator_2dmessage_2eproto();
  friend void protobuf_ShutdownFile_panoramic_2dimitator_2dmessage_2eproto();

};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:panoramicImitator.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Message_Angles Angles;
  typedef Message_Frame Frame;

  // accessors -------------------------------------------------------

  // required .panoramicImitator.Message.Angles angles = 1;
  bool has_angles() const;
  void clear_angles();
  static const int kAnglesFieldNumber = 1;
  const ::panoramicImitator::Message_Angles& angles() const;
  ::panoramicImitator::Message_Angles* mutable_angles();
  ::panoramicImitator::Message_Angles* release_angles();
  void set_allocated_angles(::panoramicImitator::Message_Angles* angles);

  // required .panoramicImitator.Message.Frame frame = 2;
  bool has_frame() const;
  void clear_frame();
  static const int kFrameFieldNumber = 2;
  const ::panoramicImitator::Message_Frame& frame() const;
  ::panoramicImitator::Message_Frame* mutable_frame();
  ::panoramicImitator::Message_Frame* release_frame();
  void set_allocated_frame(::panoramicImitator::Message_Frame* frame);

  // @@protoc_insertion_point(class_scope:panoramicImitator.Message)
 private:
  void set_has_angles();
  void clear_has_angles();
  void set_has_frame();
  void clear_has_frame();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::panoramicImitator::Message_Angles* angles_;
  ::panoramicImitator::Message_Frame* frame_;
  friend void  protobuf_InitDefaults_panoramic_2dimitator_2dmessage_2eproto_impl();
  friend void  protobuf_AddDesc_panoramic_2dimitator_2dmessage_2eproto_impl();
  friend const ::google::protobuf::uint32* protobuf_Offsets_panoramic_2dimitator_2dmessage_2eproto();
  friend void protobuf_ShutdownFile_panoramic_2dimitator_2dmessage_2eproto();

};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Message_Angles

// required double horAngle = 1;
inline bool Message_Angles::has_horangle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message_Angles::set_has_horangle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message_Angles::clear_has_horangle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message_Angles::clear_horangle() {
  horangle_ = 0;
  clear_has_horangle();
}
inline double Message_Angles::horangle() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.Angles.horAngle)
  return horangle_;
}
inline void Message_Angles::set_horangle(double value) {
  set_has_horangle();
  horangle_ = value;
  // @@protoc_insertion_point(field_set:panoramicImitator.Message.Angles.horAngle)
}

// required double vertAngle = 2;
inline bool Message_Angles::has_vertangle() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message_Angles::set_has_vertangle() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message_Angles::clear_has_vertangle() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message_Angles::clear_vertangle() {
  vertangle_ = 0;
  clear_has_vertangle();
}
inline double Message_Angles::vertangle() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.Angles.vertAngle)
  return vertangle_;
}
inline void Message_Angles::set_vertangle(double value) {
  set_has_vertangle();
  vertangle_ = value;
  // @@protoc_insertion_point(field_set:panoramicImitator.Message.Angles.vertAngle)
}

// -------------------------------------------------------------------

// Message_Frame

// required int32 height = 1;
inline bool Message_Frame::has_height() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message_Frame::set_has_height() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message_Frame::clear_has_height() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message_Frame::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 Message_Frame::height() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.Frame.height)
  return height_;
}
inline void Message_Frame::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
  // @@protoc_insertion_point(field_set:panoramicImitator.Message.Frame.height)
}

// required int32 width = 2;
inline bool Message_Frame::has_width() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message_Frame::set_has_width() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message_Frame::clear_has_width() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message_Frame::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 Message_Frame::width() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.Frame.width)
  return width_;
}
inline void Message_Frame::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
  // @@protoc_insertion_point(field_set:panoramicImitator.Message.Frame.width)
}

// -------------------------------------------------------------------

// Message

// required .panoramicImitator.Message.Angles angles = 1;
inline bool Message::has_angles() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_angles() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_angles() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_angles() {
  if (angles_ != NULL) angles_->::panoramicImitator::Message_Angles::Clear();
  clear_has_angles();
}
inline const ::panoramicImitator::Message_Angles& Message::angles() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.angles)
  return angles_ != NULL ? *angles_
                         : *::panoramicImitator::Message_Angles::internal_default_instance();
}
inline ::panoramicImitator::Message_Angles* Message::mutable_angles() {
  set_has_angles();
  if (angles_ == NULL) {
    angles_ = new ::panoramicImitator::Message_Angles;
  }
  // @@protoc_insertion_point(field_mutable:panoramicImitator.Message.angles)
  return angles_;
}
inline ::panoramicImitator::Message_Angles* Message::release_angles() {
  // @@protoc_insertion_point(field_release:panoramicImitator.Message.angles)
  clear_has_angles();
  ::panoramicImitator::Message_Angles* temp = angles_;
  angles_ = NULL;
  return temp;
}
inline void Message::set_allocated_angles(::panoramicImitator::Message_Angles* angles) {
  delete angles_;
  angles_ = angles;
  if (angles) {
    set_has_angles();
  } else {
    clear_has_angles();
  }
  // @@protoc_insertion_point(field_set_allocated:panoramicImitator.Message.angles)
}

// required .panoramicImitator.Message.Frame frame = 2;
inline bool Message::has_frame() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_frame() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_frame() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_frame() {
  if (frame_ != NULL) frame_->::panoramicImitator::Message_Frame::Clear();
  clear_has_frame();
}
inline const ::panoramicImitator::Message_Frame& Message::frame() const {
  // @@protoc_insertion_point(field_get:panoramicImitator.Message.frame)
  return frame_ != NULL ? *frame_
                         : *::panoramicImitator::Message_Frame::internal_default_instance();
}
inline ::panoramicImitator::Message_Frame* Message::mutable_frame() {
  set_has_frame();
  if (frame_ == NULL) {
    frame_ = new ::panoramicImitator::Message_Frame;
  }
  // @@protoc_insertion_point(field_mutable:panoramicImitator.Message.frame)
  return frame_;
}
inline ::panoramicImitator::Message_Frame* Message::release_frame() {
  // @@protoc_insertion_point(field_release:panoramicImitator.Message.frame)
  clear_has_frame();
  ::panoramicImitator::Message_Frame* temp = frame_;
  frame_ = NULL;
  return temp;
}
inline void Message::set_allocated_frame(::panoramicImitator::Message_Frame* frame) {
  delete frame_;
  frame_ = frame;
  if (frame) {
    set_has_frame();
  } else {
    clear_has_frame();
  }
  // @@protoc_insertion_point(field_set_allocated:panoramicImitator.Message.frame)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace panoramicImitator

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_panoramic_2dimitator_2dmessage_2eproto__INCLUDED
